---
title: "Chapter 12: Factors with forcats"
author: "Matt Russell"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(forcats)
```

## Load the gss_cat dataset and plot it:

```{r}
forcats::gss_cat
gss_cat

# Count by race
gss_cat %>% 
  count(race)

# Plot by race
ggplot(gss_cat, aes(race))+
  geom_bar()

# Plot by race, including NA
ggplot(gss_cat, aes(race))+
  geom_bar()+
  scale_x_discrete(drop=F)
```

## Exercises


```{r}
# 1. bar plot labels on x-axis are overlapping. I used coord_flip to list them on the y-axis.  

gss_cat %>% 
  count(rincome)

ggplot(gss_cat, aes(rincome))+
  geom_bar()+
  coord_flip()+
  scale_x_discrete(drop=F)

# 2. Protestant is most common. 

gss_cat %>% 
  count(relig)

ggplot(gss_cat, aes(relig))+
  geom_bar()+
  coord_flip()+
  scale_x_discrete(drop=F)

# Independent is the most common party id.
gss_cat %>% 
  count(partyid)


ggplot(gss_cat, aes(partyid))+
  geom_bar()+
  coord_flip()+
  scale_x_discrete(drop=F)

# 3. The denom applies mostly to Protestants. We can group by, filter, and count to see the Protestant denominations.

# We can use facetting to see that the pretstant religion has a number of denominations within it. 

relig_denom<-gss_cat %>% 
  group_by(relig,denom) %>% 
  filter(denom != "Not applicable") %>% 
  count()
relig_denom

p.denom<-gss_cat %>% 
  group_by(relig,denom) %>% 
  count() %>% 
  #filter(denom != "Not applicable") %>% 
  ggplot(aes(denom,n))+
  geom_bar(stat="identity")+
  coord_flip()+
  facet_wrap(~relig)
p.denom
```

## Here's how fct_reorder() works:

```{r}
relig_summary <- gss_cat %>%
  group_by(relig) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

ggplot(relig_summary, aes(tvhours, relig)) + geom_point()

ggplot(relig_summary, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()

# Also:
relig_summary %>%
  mutate(relig = fct_reorder(relig, tvhours)) %>%
  ggplot(aes(tvhours, relig)) +
    geom_point()

# Income vs age:
rincome_summary <- gss_cat %>%
  group_by(rincome) %>%
  summarise(
    age = mean(age, na.rm = TRUE),
    tvhours = mean(tvhours, na.rm = TRUE),
    n = n()
  )

ggplot(rincome_summary, aes(age, fct_reorder(rincome, age))) + geom_point()
```

## Here's how fct_relevel() works:

```{r}
ggplot(rincome_summary, aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()
```

## Here's how fct_infreq() works (and fct_rev()):

```{r}
gss_cat %>% 
  mutate(marital = marital %>% fct_infreq()) %>% 
           ggplot(aes(marital))+
           geom_bar()

gss_cat %>% 
  mutate(marital = marital %>% fct_infreq() %>% fct_rev()) %>% 
           ggplot(aes(marital))+
           geom_bar()
```


## Exercises

```{r}
# 1. The mean may not be a good value that describes the data because it is right skewed. The median will do.

gss_cat %>% 
  ggplot(aes("",tvhours))+
  geom_boxplot()

gss_cat %>% 
  summarize(mean.tv=mean(tvhours,na.rm=T),
            median.tv=median(tvhours,na.rm=T))

# 2. 
levels(gss_cat$marital)
# marital: order is arbitrary

levels(gss_cat$race)
# race: order is arbitrary

levels(gss_cat$rincome)
# rincome: order is principled

levels(gss_cat$partyid)
# partyid: order is principled, but what to do with "other party" and "independent"

levels(gss_cat$relig)
# relig: order is arbirary

levels(gss_cat$denom)
# denom: order is arbitrary, but should be group within relig

# 3. By default, fct_relevel adds values to values after the last one (after=0 is the default).
ggplot(rincome_summary, aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()

ggplot(rincome_summary, aes(age, fct_relevel(rincome, "$8000 to 9999"))) +
  geom_point()

ggplot(rincome_summary, aes(age, fct_relevel(rincome, "Not applicable", after = 6))) +
  geom_point()
```

## Here's how fct_recode() and fct_lump() and fct_collapse() work:

```{r}
gss_cat %>% 
  count(partyid)

gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat"
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(partyid = fct_recode(partyid,
    "Republican, strong"    = "Strong republican",
    "Republican, weak"      = "Not str republican",
    "Independent, near rep" = "Ind,near rep",
    "Independent, near dem" = "Ind,near dem",
    "Democrat, weak"        = "Not str democrat",
    "Democrat, strong"      = "Strong democrat",
    "Other"                 = "No answer",
    "Other"                 = "Don't know",
    "Other"                 = "Other party"
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(partyid = fct_collapse(partyid,
    other = c("No answer", "Don't know", "Other party"),
    rep = c("Strong republican", "Not str republican"),
    ind = c("Ind,near rep", "Independent", "Ind,near dem"),
    dem = c("Not str democrat", "Strong democrat")
  )) %>%
  count(partyid)

gss_cat %>%
  mutate(relig = fct_lump(relig)) %>%
  count(relig)

## Use the n parameter to specify how many values you want to keep (exclusing Other)
gss_cat %>%
  mutate(relig = fct_lump(relig, n = 10)) %>%
  count(relig, sort = TRUE) %>%
  print(n = Inf)

gss_cat %>%
  mutate(relig = fct_lump(relig, n = 4)) %>%
  count(relig, sort = TRUE) %>%
  print(n = Inf)

```


```{r}
# 1. It looks like Republicans have decreased, Democrats stayed the same, and Independents have increased
gss_cat %>% 
    mutate(partyid2 = fct_collapse(partyid,
    other = c("No answer", "Don't know", "Other party"),
    rep = c("Strong republican", "Not str republican"),
    ind = c("Ind,near rep", "Independent", "Ind,near dem"),
    dem = c("Not str democrat", "Strong democrat")
  )) %>%
  filter(partyid2 != c("other")) %>% 
  group_by(year) %>% 
  count(partyid2) %>%
  mutate(prop = n/ sum(n)) %>% 
  ggplot(aes(year,prop,col=partyid2))+
  geom_point()+
  geom_line()

# 2.
levels(gss_cat$rincome)

# Try fct_collapse and group them into high, medium, and low earners

gss_cat %>%
  mutate(rincome = fct_collapse(rincome,
    `Other` = c("No answer", "Don't know","Refused","Not applicable"),
    `> $10000` = c("$25000 or more", "$20000 - 24999", "$15000 - 19999", "$10000 - 14999"),
    `$5000 to $10000` = c("$8000 to 9999", "$7000 to 7999", "$6000 to 6999", "$5000 to 5999"),
    `< $5000` = c("$4000 to 4999", "$3000 to 3999", "$1000 to 2999", "Lt $1000")
  )) %>%
  ggplot(aes(x=rincome))+
  coord_flip()+
  geom_bar()
```