---
title: "chap1"
author: "Matt Russell"
date: "8/2/2019"
output: html_document
---

Load the mpg data set

```{r setup, include=FALSE}
library(tidyverse)
mpg
```

Plot engine size vs fuel efficiency
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))
```

Exercises
```{r}

ggplot(data=mpg)
# 1. We get a blank plot!

dim(mpg)
nrow(mpg)
ncol(mpg)
# 2. There are 234 rows and 11 columns in mtcars.

?mpg
# 3. drv represents: f = front-wheel drive, r = rear wheel drive, 4 = 4wd

ggplot(data = mpg)+
  geom_point(mapping = aes (x=cyl, y=hwy))

# 4. See plot.

ggplot(data = mpg)+
  geom_point(mapping = aes (x=class, y=drv))

# 5. There is only a point for each drv-class combination. It does not show how many observations are in each.
```

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy, color=class))

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy, shape=class))

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy),color="blue")
```


Exercises
```{r}
# 1. color="blue" is inside the aes() statement, it should be outside

# 2. Categorical: manufacturer, model, year, cyl, drv, trans, fl, class
  # Continuous: displ, cty, hwy

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy, size=cty))
# 3. continuous variable cannot be mapped to shape
 #continuous variable mapped to color provide a grdient of blue
 #continuous variable mapped to size provides different sized points depending on the continuous variable

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy, size=cty,color=cty))
# 4. You end up with two different legends for each aesthetic when you map more that one aesthetic to the same variable.

?geom_point
ggplot(mpg)+
  geom_point(mapping= aes(x=displ, y=hwy), shape = 21, stroke = 2)
# 5. The stroke aesthetic modifies the width of the border. It works for shapes that have a border.
# border

ggplot(mpg)+
  geom_point(mapping= aes(x=displ, y=hwy, color = displ<5))
# 6. It colors all engines with an engine displacement less than 5.

```

```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_wrap(~class,nrow=2)

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_grid(drv~cyl)
```

Exercises
```{r}
ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_wrap(~cty,nrow=2)
# 1. It looks like it attempts to treat the continuos variable as a factor.

ggplot(data = mpg)+
  geom_point(mapping = aes (x=drv, y=cyl))
# 2. Empty cells mean there are no observations in that group

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_grid(drv~.)

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_grid(.~cyl)
# 3. Adding the . grids the factors to appear vertically or horizontally.

ggplot(data = mpg)+
  geom_point(mapping = aes (x=displ, y=hwy))+
  facet_wrap(~class,nrow=2)
# 4. It quickly allows you to see the range within a given car class. Disadvantages is you can't see the within-class range of data due to the extended scales of the axes. We could add a shape or color for a different attribute if we had a bigger data set.

?facet_wrap
# 5. nrow and ncol set the number of rows and columns in the facetting. facet_grid() doesn't have that option because it allows you to plot multiple variables in the grid. Can also change scales, labels with facet_wrap().

?facet_grid
# 6. Reading across columns from left to right is easier on the eye than from up to down.
```

```{r}
ggplot(data = mpg)+
  geom_smooth(mapping = aes (x=displ, y=hwy))

ggplot(data = mpg)+
  geom_smooth(mapping = aes (x=displ, y=hwy,linetype=drv))

ggplot(data = mpg, mapping = aes (x=displ, y=hwy))+
  geom_point(aes(color=class))+
    geom_smooth()

ggplot(data = mpg, mapping = aes (x=displ, y=hwy))+
  geom_point(aes(color=class))+
    geom_smooth(data=filter(mpg, class=="subcompact"),se=FALSE)
```

Exercises
```{r}
# 1. geom_line, geom_boxplot, geom_histogram, geom_ribbon

# 2. scatterplot with color by drv, smoothed line by drv with no se
ggplot(data = mpg, mapping = aes (x=displ, y=hwy, color=drv))+
  geom_point()+
    geom_smooth(se=FALSE,show.legend=FALSE)

# 3. show.legend=FALSE removes the line in the legend key. It makes it easier to see the points 

# 4. se turns on/off the 95% confidence limits around the smoothed lines.

ggplot(data = mpg, mapping = aes (x=displ, y=hwy))+
  geom_point()+
    geom_smooth()

ggplot()+
  geom_point(data = mpg, mapping = aes (x=displ, y=hwy))+
    geom_smooth(data = mpg, mapping = aes (x=displ, y=hwy))

# 5. They will look the same, there's no difference in the mapping.

ggplot(data = mpg, mapping = aes (x=displ, y=hwy))+
  geom_point()+
    geom_smooth(se=F)

ggplot(data = mpg, mapping = aes (x=displ, y=hwy))+
  geom_point()+
    geom_smooth(aes (x=displ, y=hwy,group=drv),se=F,show.legend = F)


ggplot(data = mpg, mapping = aes (x=displ, y=hwy,color=drv))+
  geom_point()+
    geom_smooth(se=F)

ggplot()+
  geom_point(mpg, mapping = aes (x=displ, y=hwy, color=drv))+
    geom_smooth(mpg, mapping = aes (x=displ, y=hwy),se=F)

ggplot()+
  geom_point(mpg, mapping = aes (x=displ, y=hwy, color=drv))+
    geom_smooth(mpg, mapping = aes (x=displ, y=hwy, linetype=drv),se=F)

ggplot(mpg, mapping = aes (x=displ, y=hwy, color=drv))+
  geom_point()

```

```{r}
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut))
  
#Use stat_count()
ggplot(data=diamonds)+
  stat_count(mapping = aes(x=cut))

#plot poportion

#Use stat_count()
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, y=..prop.., group = 1))


#Use stat_summary()
ggplot(data=diamonds)+
  stat_summary(mapping = aes(x=cut, y=depth),
               fun.ymin = min,
               fun.ymax = max,
               fun.y = median)
```

Excercises
```{r}
?stat_summary

ggplot(data = diamonds) +
  geom_pointrange(
    mapping = aes(x = cut, y = depth),
    stat = "summary"
  )

#1. The default geom is  geom = "pointrange",

#2. geom_col() gives the heights of the bars to represent values in the data. geom_bar() makes the height of the bar proportional to the number of cases in each group

#3. geom_boxplot() and stat_boxplot(); geom_histogram() and stat_bin(), etc

#4. stat_smooth compuetes the predicted vales, confidence intervals around the mean, and the standard error. The method ="" and fomula y~x control its behavior.

ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, y=..prop..))

ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, y=..prop.., fill = color))

#5. Wow, not including group = 1 doesn't separate the diamond cuts into each group.
```

```{r}
ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, color=cut))

ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, fill=clarity))

ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, fill=clarity),position = "fill")

ggplot(data=diamonds)+
  geom_bar(mapping = aes(x=cut, fill=clarity),position = "dodge")

ggplot(data=mpg)+
  geom_point(mapping = aes(x=displ,y=hwy), position = "jitter")
```

Exercises
```{r}
ggplot(data=mpg)+
  geom_point(mapping = aes(x=cty,y=hwy))

ggplot(data=mpg)+
  geom_point(mapping = aes(x=cty,y=hwy),position="jitter")

#1. There are a lot of values with the same cty-hwy mileage pairs. You can use jitter.

#2. The jittering depends on width and height of the jittering.

#3. goem_jitter() is best for scatter plots. geom_count() works best for discrete data and counts the number of observations at each level. 

ggplot(data=mpg)+
  geom_boxplot(mapping = aes(x=drv,y=cty))

#4. Default position for geom_boxplot() is dodge2. 
```


```{r}
usa<-map_data("usa")
ggplot(usa,aes(long,lat,group=group))+
  geom_polygon(fill="white",color="black")
ggplot(usa,aes(long,lat,group=group))+
  geom_polygon(fill="white",color="black")+
  coord_quickmap()
```

Exercises
```{r}
ggplot(data=mpg)+
  geom_bar(mapping = aes(x=drv,fill=class))


ggplot(data=mpg)+
  geom_bar(mapping = aes(x=drv,fill=class))+
  coord_polar()

#1. Code above turns a stacked bar chart into a pie chart.

#2. labs() allows you to add/remove labels to a ggplot figure.

?coord_quickmap
?coord_map

#3. coord_quickmap() projects maps with an aspect ratio approximation. coord_map() projects maps with the correct mercator approximation.


ggplot(data=mpg)+
  geom_point(mapping = aes(x=cty,y=hwy))+
  geom_abline()+
  coord_fixed()
#4. The graph indicates the mpg on the highway is always greater than mpg in the city for all cars. coord_fixed() allows you to easily see the trend in the 1:1 line (what geom_abline provides).
```
