---
title: "Chapter 11-Strings with stringr"
author: "Matt Russell"
date: "10/21/2019"
output: html_document
---

Focus on regular expressions, or *regexps*


```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
```

All strinr functions start with *str_*
```{r setup, include=FALSE}
string1<- "A string."
string2<- 'A "string" within a string.'
c("one","two","three")

# Calculate number of charcters in a string
str_length(c("one","two","three"))

# Combine strings
str_c("one","two","three")
str_c("one","two","three", sep="99")

name <- "Matt"
time_of_day <- "morning"
birthday <- TRUE

str_c("Good ", time_of_day, " " , name,
      if(birthday) " and Happy Birthday",
      "!")

str_c(c("one","two","three"))
str_c(c("one","two","three"), collapse=",")

#subsetting strings
x<-c("Astros", "Nationals")
str_sub(x,1,4)

# Change to lower/uppercase
str_to_lower(x)
str_to_upper(x)

# Sort
str_sort(x)

str_sort(x, decreasing=T)
```

Exercises
```{r}
# 1. paste() and paste0() concatenate vectors. str_c is the equivalent in stringr.
?paste

# 2. sep puts space between different values in a string, while collapse creates a long string
str_c(c("one","two","three"))
str_c(c("one","two","three"), sep = " ")
str_c(c("one","two","three"), collapse=" ")

# 3. It takes the closet of the the two values if there is an even number of values in a string. 
x<-"New York Mets"
str_length(x)
str_sub(x,2,8)
str_sub(x,str_length(x)/2)

x <- c("a", "abc", "abcd", "abcde", "abcdef")
L <- str_length(x)
m <- ceiling(L / 2)
str_sub(x, m, m)

# 4. str_wrap wraps text to fit in certain widths and indents  
?str_wrap
str_wrap(c("New York Mets", "New York Yankees","New York Mets", "New York Yankees","New York Mets", "New York Yankees"), width=10)

# 5. str_trim removes whitespace from the start and end of a string. str_c keeps the whitespace and can be considered the opposite. Also, str_pad adds whitespace
?str_trim
str_trim(c("      New York Mets       ", "  New York Yankees  "))
str_c(c("      New York Mets       ", "  New York Yankees  "))

str_pad(c("New York Mets", "New York Yankees"), 40,side=c("both"))

#6. 
```


Matching patterns with regexps

```{r}
x<- c("apple", "banana", "pear")

str_view(x, "ana")
str_view(x, ".a.")

```

Exercises
```{r}
# 1.

```

Anchors match the beginning/end of strings
```{r}
x<- c("apple", "banana", "pear")

str_view(x, "^p")

str_view(x, "r$")

x<-c("New York Mets", "New York Yankees")
str_view(x, "New York")
str_view(x, "^New York Mets$")

```


Exercises
```{r}
# 1.
str_view(c("$^$", "ab$^$sfas"), "^\\$\\^\\$$", match = TRUE)

#2. 
str_view(stringr::words, "^y", match = TRUE)

str_view(stringr::words, "x$", match = TRUE)

str_view(stringr::words, "^...$", match = TRUE)

str_view(stringr::words, ".......", match = TRUE)

```

Exercises
```{r}
# 1.
str_subset(stringr::words, "^[aeiou]", match=T)
str_subset(stringr::words, "^[^aeiou]+$")
str_subset(stringr::words, "[^e]ed$")
str_subset(stringr::words, "i(ng|se)$")


#2. 
length(str_subset(stringr::words, "(cei|[^c]ie)"))

#3. 
str_view(stringr::words, "[^qu]", match = TRUE)


#4. Probably ou” instead of “o”.


#5.
x <- c("123-456-7890", "1235-2351")
str_view(x, "\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d")
```

Exercises
```{r}
#1. 

#2.

#3. 

# All words starting with three consanants
str_view(words, "^[^aeiou]{3}", match = TRUE)

# Three or more vowels in a row:
str_view(words, "[aeiou]{3,}", match = TRUE)

# Two or more vowel-consanant pairs in a row
str_view(words, "([aeiou][^aeiou]){2,}", match = TRUE)

#4. 


```

Exercises
```{r}
#1.
# a.  (.)\1\1: The same character appearing three times in a row. E.g. "aaa"
# b. "(.)(.)\\2\\1": A pair of characters followed by the same pair of characters in reversed order. E.g. "abba".
# c. (..)\1: Any two characters repeated. E.g. "a1a1".
# d. "(.).\\1.\\1": A character followed by any character, the original character, any other character, the original character again. E.g. "abaca", "b8b.b".
# e. "(.)(.)(.).*\\3\\2\\1" Three characters followed by zero or more characters of any kind followed by the same three characters but in reverse order. E.g. "abcsgasgddsadgsdgcba" or "abccba" or "abc1cba".

#2.
# Words that start and end with same character
str_subset(words, "^(.)((.*\\1$)|\\1?$)")

# Repeated pair of letters
str_subset("church", "([A-Za-z][A-Za-z]).*\\1")

# One letter in three places
str_subset(words, "([a-z]).*\\1.*\\1")

```

str_detect finds patterns within strings
```{r}
x<-c("Mets", "Yankees", "Dodgers", "Giants")
str_detect(x,"k")
sum(str_detect(x,"k"))
mean(str_detect(x,"k"))

str_count(x, "a")
```

Exercises
```{r}
# 1. 
str_detect(words, "^x|x$")

str_subset(words, "^[aeiou].*[^aeiou]$") 

words[str_detect(words, "a") &
  str_detect(words, "e") &
  str_detect(words, "i") &
  str_detect(words, "o") &
  str_detect(words, "u")]

vowels <- str_count(words, "[aeiou]")
words[which(vowels == max(vowels))]

prop_vowels <- str_count(words, "[aeiou]") / str_length(words)
words[which(prop_vowels == max(prop_vowels))]
```

```{r}
head(sentences)

colors <- c("red", "orange", "green", "blue")
colors_match <- str_c(colors, collapse = "|")
colors_match

has_color<-str_subset(sentences, colors_match)
matches<-str_extract(has_color, colors_match)
head(matches)
```

Exercises:
```{r}
#1.

#2.
str_extract(sentences, "[A-ZAa-z]+") %>% head()

pattern <- "\\b[A-Za-z]+ing\\b"
sentences_with_ing <- str_detect(sentences, pattern)
unique(unlist(str_extract_all(sentences[sentences_with_ing], pattern))) %>%
  head()

unique(unlist(str_extract_all(sentences, "\\b[A-Za-z]{3,}s\\b"))) %>%
  head()
```

Exercises:
```{r}
#1.
numword <- "\\b(one|two|three|four|five|six|seven|eight|nine|ten) +(\\w+)"
sentences[str_detect(sentences, numword)] %>%
  str_extract(numword)
#2.
contraction <- "([A-Za-z]+)'([A-Za-z]+)"
sentences[str_detect(sentences, contraction)] %>%
  str_extract(contraction) %>%
  str_split("'")

```

Exercises:
```{r}
#1.
str_replace_all("past/present/future", "/", "\\\\")
#2.
replacements <- c(
  "A" = "a", "B" = "b", "C" = "c", "D" = "d", "E" = "e",
  "F" = "f", "G" = "g", "H" = "h", "I" = "i", "J" = "j",
  "K" = "k", "L" = "l", "M" = "m", "N" = "n", "O" = "o",
  "P" = "p", "Q" = "q", "R" = "r", "S" = "s", "T" = "t",
  "U" = "u", "V" = "v", "W" = "w", "X" = "x", "Y" = "y",
  "Z" = "z"
)
lower_words <- str_replace_all(words, pattern = replacements)
head(lower_words)
#3.
swapped <- str_replace_all(words, "^([A-Za-z])(.*)([a-z])$", "\\3\\2\\1")
```

Exercises
```{r}
#1.
x <- c("apples, pears, and bananas")
str_split(x, ", +(and +)?")[[1]]

#2.
sentence <- "The quick (“brown”) fox can’t jump 32.3 feet, right?"
str_split(sentence, " ")

#3. 
str_split("ab. cd|agt", "")[[1]]
#It splits the string into individual characters.

```

Exercises
```{r}
#1.
str_subset(c("a\\b", "ab"), "\\\\")
str_subset(c("a\\b", "ab"), fixed("\\"))

#2.
tibble(word = unlist(str_extract_all(sentences, boundary("word")))) %>%
  mutate(word = str_to_lower(word)) %>%
  count(word, sort = TRUE) %>%
  head(5)
```

Exercises
```{r}
#1.
stri_count_words(head(sentences))

stri_duplicated(c(
  "the", "brown", "cow", "jumped", "over",
  "the", "lazy", "fox"
))

stri_rand_strings(4, 5)

stri_rand_shuffle("The brown fox jumped over the lazy cow.")

stri_rand_lipsum(1)

#2.
library(stringi)
string1 <- c("hladny", "chladny")
stri_sort(string1, locale = "pl_PL")

stri_sort(string1, locale = "sk_SK")


stri_sort(string1, opts_collator = stri_opts_collator(locale = "pl_PL"))
stri_sort(string1, opts_collator = stri_opts_collator(locale = "sk_SK"))

string2 <- c("number100", "number2")

stri_sort(string2)

stri_sort(string2, opts_collator = stri_opts_collator(numeric = TRUE))

```
